### ISSUE TITLE
la barre loading ne monte pas en pourcentage

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/golden-age.io#12]
sur la première page, il y a loading, mais ça ne progresse pas en pourcentage.

**Comment by LeonLenclos** [comment]
Ouais c'est parce que ya un seul fichier a charger pour l'instant donc ça va direct de 0% (0 fichiers chargés) à 100% (1 fichier chargés)

On aura d'autres pourcentages des que yaura plus de fichiers à charger.
