### ISSUE TITLE
Panel Fin de partie

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/golden-age.io#13]
## afficher WINNER / LOOSER en gros

ou YOU WIN / YOU LOOSE
que ça se voit bien, sinon on peut croire au bug mais si ok un joueur a perdu

**Comment by LeonLenclos** [comment]
Utiliser la colonne de droite (sélection) pour afficher un panel "end"

# Information :

## En petit, l'explication du résultat

"All your units/opponent's units are dead"
"Time is up and you have more/less gold than your opponent"
Ou
"You/Your opponent have/has reached 500 gold"
Mais aussi
"The last units died at the same time"

"You have reached 500 gold at the same time"

"The time is up and you have the same amount of gold"

## en gros, le résultat

"You win"/"you loose"/"It's a draw!"

## Les options

un bouton "quit"

Et 

Un bouton "Request a rematch"

Ou en petit : "Your opponent to propose a rematch"

Et un bouton "Accept the rematch"
