### ISSUE TITLE
faire correspondre le côté où tu commence avec ta barre d'or

### ISSUE THREAD

**Issue by dracdrac** [LeonLenclos/golden-age.io#16]
ça embrouille le fait de commencer du côté gauche si ta barre d'or se situe à droite

**Comment by LeonLenclos** [comment]
C'est un bug du au fait que le `break` à qui suit
          this.start_positions = [pos, symetric(pos)];
dans world.js ne fais pas sortir de la boucle 2d mais seulement de la boucle du y
 !!!!!

**Comment by LeonLenclos** [comment]
C'est un bug du au fait que le `break` à qui suit
          this.start_positions = [pos, symetric(pos)];
dans world.js ne fais pas sortir de la boucle 2d mais seulement de la boucle du y
 !!!!!
